#!/usr/bin/env node

/**
 * Enterprise Authentication Package - Automated Setup Script
 * Configures the authentication system in target repositories
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

class AuthPackageSetup {
  constructor() {
    this.packageRoot = __dirname + '/..';
    this.targetRoot = process.cwd();
    this.isInTargetRepo = !this.targetRoot.includes('auth-package');
  }

  async run() {
    console.log('🔐 Enterprise Authentication Package Setup');
    console.log('==========================================');
    
    try {
      await this.validateEnvironment();
      await this.installDependencies();
      await this.setupDatabaseTables();
      await this.copyConfigFiles();
      await this.updatePackageJson();
      await this.validateInstallation();
      
      console.log('\n✅ Authentication package setup complete!');
      console.log('\nNext steps:');
      console.log('1. Configure environment variables in .env');
      console.log('2. Run: npm run db:migrate');
      console.log('3. Run: npm test');
      console.log('4. Import auth components in your application');
      
    } catch (error) {
      console.error('\n❌ Setup failed:', error.message);
      process.exit(1);
    }
  }

  async validateEnvironment() {
    console.log('\n📋 Validating environment...');
    
    // Check Node.js version
    const nodeVersion = process.version;
    const majorVersion = parseInt(nodeVersion.slice(1).split('.')[0]);
    if (majorVersion < 16) {
      throw new Error(`Node.js 16+ required, found ${nodeVersion}`);
    }
    console.log(`✓ Node.js ${nodeVersion}`);

    // Check if we're in a git repository
    try {
      execSync('git rev-parse --git-dir', { stdio: 'pipe' });
      console.log('✓ Git repository detected');
    } catch (error) {
      throw new Error('Must be run in a git repository');
    }

    // Check for package.json in target
    if (!fs.existsSync(path.join(this.targetRoot, 'package.json'))) {
      throw new Error('package.json not found in target repository');
    }
    console.log('✓ Target package.json found');

    // Check for PostgreSQL availability
    try {
      if (process.env.DATABASE_URL) {
        console.log('✓ DATABASE_URL configured');
      } else {
        console.log('⚠️  DATABASE_URL not configured - you\'ll need to set this');
      }
    } catch (error) {
      console.log('⚠️  Database configuration will be needed');
    }
  }

  async installDependencies() {
    console.log('\n📦 Installing authentication dependencies...');
    
    const requiredDeps = [
      'bcrypt',
      'jsonwebtoken', 
      'express-session',
      'express-rate-limit',
      'helmet',
      'cors',
      'nodemailer',
      'speakeasy',
      'qrcode',
      'drizzle-orm',
      'drizzle-kit',
      '@neondatabase/serverless',
      'zod'
    ];

    const requiredDevDeps = [
      '@types/bcrypt',
      '@types/jsonwebtoken',
      '@types/express-session',
      '@types/nodemailer',
      '@types/speakeasy',
      'supertest'
    ];

    try {
      // Install production dependencies
      console.log('Installing production dependencies...');
      execSync(`npm install ${requiredDeps.join(' ')}`, { 
        stdio: 'inherit',
        cwd: this.targetRoot 
      });

      // Install dev dependencies  
      console.log('Installing development dependencies...');
      execSync(`npm install --save-dev ${requiredDevDeps.join(' ')}`, { 
        stdio: 'inherit',
        cwd: this.targetRoot 
      });

      console.log('✓ Dependencies installed');
    } catch (error) {
      throw new Error(`Failed to install dependencies: ${error.message}`);
    }
  }

  async setupDatabaseTables() {
    console.log('\n🗄️  Setting up database tables...');
    
    const migrationScript = `
-- Authentication Package Database Schema
-- Generated by setup script

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  role VARCHAR(50) DEFAULT 'user',
  is_active BOOLEAN DEFAULT true,
  email_verified BOOLEAN DEFAULT false,
  two_factor_enabled BOOLEAN DEFAULT false,
  two_factor_secret VARCHAR(255),
  last_login_at TIMESTAMP WITH TIME ZONE,
  last_login_ip INET,
  failed_login_attempts INTEGER DEFAULT 0,
  locked_until TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_sessions (
  id SERIAL PRIMARY KEY,
  session_id VARCHAR(255) UNIQUE NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  data JSONB,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  token VARCHAR(255) UNIQUE NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  used_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(100) NOT NULL,
  resource VARCHAR(100),
  ip_address INET,
  user_agent TEXT,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rate_limits (
  id SERIAL PRIMARY KEY,
  identifier VARCHAR(255) NOT NULL,
  action VARCHAR(100) NOT NULL,
  count INTEGER DEFAULT 1,
  window_start TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_user_sessions_session_id ON user_sessions(session_id);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON user_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_token ON password_reset_tokens(token);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user_id ON password_reset_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_rate_limits_identifier ON rate_limits(identifier);
CREATE INDEX IF NOT EXISTS idx_rate_limits_action ON rate_limits(action);
`;

    // Write migration file
    const migrationsDir = path.join(this.targetRoot, 'migrations');
    if (!fs.existsSync(migrationsDir)) {
      fs.mkdirSync(migrationsDir, { recursive: true });
    }

    const migrationFile = path.join(migrationsDir, `${Date.now()}_auth_package_setup.sql`);
    fs.writeFileSync(migrationFile, migrationScript);
    console.log(`✓ Migration file created: ${migrationFile}`);

    // Create drizzle config if it doesn't exist
    const drizzleConfigPath = path.join(this.targetRoot, 'drizzle.config.ts');
    if (!fs.existsSync(drizzleConfigPath)) {
      const drizzleConfig = `
import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  schema: './auth-package/shared/schema.ts',
  out: './migrations',
  dialect: 'postgresql',
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
});
`;
      fs.writeFileSync(drizzleConfigPath, drizzleConfig);
      console.log('✓ Drizzle config created');
    }
  }

  async copyConfigFiles() {
    console.log('\n📄 Copying configuration files...');

    // Create .env.example if it doesn't exist
    const envExamplePath = path.join(this.targetRoot, '.env.example');
    if (!fs.existsSync(envExamplePath)) {
      const envExample = `
# Database Configuration
DATABASE_URL=postgresql://username:password@localhost:5432/your_database
PGHOST=localhost
PGPORT=5432
PGUSER=your_username
PGPASSWORD=your_password
PGDATABASE=your_database

# Authentication Configuration
SESSION_SECRET=your-super-secure-session-secret-change-this
JWT_SECRET=your-jwt-secret-for-tokens-change-this

# Email Configuration (for password reset)
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=your-email@gmail.com
SMTP_PASS=your-app-password

# Security Configuration
NODE_ENV=development
SECURE_COOKIES=false
FORCE_HTTPS=false
CORS_ORIGIN=http://localhost:3000

# Rate Limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_ATTEMPTS=5

# Two-Factor Authentication
TWO_FACTOR_SERVICE_NAME=Your App Name
`;
      fs.writeFileSync(envExamplePath, envExample);
      console.log('✓ .env.example created');
    }

    // Copy middleware integration example
    const middlewareExamplePath = path.join(this.targetRoot, 'auth-integration-example.js');
    const middlewareExample = `
/**
 * Authentication Integration Example
 * Copy this code to your main server file
 */

import express from 'express';
import { setupAuth, authMiddleware, adminMiddleware } from './auth-package/server/middleware.js';
import { authRoutes } from './auth-package/server/routes.js';

const app = express();

// Setup authentication (must be early in middleware chain)
await setupAuth(app);

// Mount authentication routes
app.use('/api/auth', authRoutes);

// Protect your existing routes
app.get('/api/protected', authMiddleware, (req, res) => {
  res.json({ 
    message: 'This route requires authentication',
    user: req.user 
  });
});

// Admin-only routes
app.get('/api/admin', adminMiddleware, (req, res) => {
  res.json({ 
    message: 'Admin access required',
    user: req.user 
  });
});

// Error handling for auth
app.use((err, req, res, next) => {
  if (err.name === 'UnauthorizedError') {
    res.status(401).json({ message: 'Authentication required' });
  } else {
    next(err);
  }
});
`;
    fs.writeFileSync(middlewareExamplePath, middlewareExample);
    console.log('✓ Integration example created');

    // Copy React integration example
    const reactExamplePath = path.join(this.targetRoot, 'auth-react-example.tsx');
    const reactExample = `
/**
 * React Authentication Integration Example
 * Copy relevant parts to your React application
 */

import React from 'react';
import { AuthProvider, useAuth } from './auth-package/client/context/AuthContext';
import { LoginForm, RegisterForm } from './auth-package/client/components';

// Main App with Auth Provider
function App() {
  return (
    <AuthProvider>
      <Router>
        <Routes>
          <Route path="/login" element={<LoginForm />} />
          <Route path="/register" element={<RegisterForm />} />
          <Route path="/dashboard" element={<ProtectedDashboard />} />
        </Routes>
      </Router>
    </AuthProvider>
  );
}

// Protected component example
function ProtectedDashboard() {
  const { user, logout, isLoading } = useAuth();
  
  if (isLoading) return <div>Loading...</div>;
  
  if (!user) {
    return <Navigate to="/login" />;
  }
  
  return (
    <div>
      <h1>Welcome, {user.email}</h1>
      <p>Role: {user.role}</p>
      <button onClick={logout}>Logout</button>
    </div>
  );
}

// Login form usage
function LoginPage() {
  return (
    <div>
      <h1>Login</h1>
      <LoginForm 
        onSuccess={() => window.location.href = '/dashboard'}
        onError={(error) => console.error(error)}
      />
    </div>
  );
}

export default App;
`;
    fs.writeFileSync(reactExamplePath, reactExample);
    console.log('✓ React example created');
  }

  async updatePackageJson() {
    console.log('\n📝 Updating package.json scripts...');

    const packageJsonPath = path.join(this.targetRoot, 'package.json');
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

    // Add authentication-related scripts
    const authScripts = {
      'db:migrate': 'drizzle-kit push:pg',
      'db:generate': 'drizzle-kit generate:pg',
      'db:studio': 'drizzle-kit studio',
      'auth:test': 'npm test -- auth',
      'auth:setup': 'node auth-package/scripts/setup.js',
      'security:audit': 'npm audit && npm run auth:test'
    };

    packageJson.scripts = { ...packageJson.scripts, ...authScripts };

    fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2));
    console.log('✓ Package.json scripts updated');
  }

  async validateInstallation() {
    console.log('\n🔍 Validating installation...');

    // Check that all required files exist
    const requiredFiles = [
      'auth-package/server/middleware.js',
      'auth-package/server/routes.js',
      'auth-package/client/context/AuthContext.tsx',
      'auth-package/client/components/index.ts',
      'auth-package/shared/schema.ts'
    ];

    for (const file of requiredFiles) {
      const filePath = path.join(this.targetRoot, file);
      if (!fs.existsSync(filePath)) {
        console.log(`⚠️  ${file} not found - check auth package structure`);
      } else {
        console.log(`✓ ${file}`);
      }
    }

    // Test database connection if URL is available
    if (process.env.DATABASE_URL) {
      try {
        // This would test the database connection
        console.log('✓ Database connection test skipped (configure DATABASE_URL first)');
      } catch (error) {
        console.log('⚠️  Database connection test failed - check DATABASE_URL');
      }
    }

    console.log('✓ Installation validation complete');
  }
}

// Run setup if called directly
if (require.main === module) {
  const setup = new AuthPackageSetup();
  setup.run();
}

module.exports = AuthPackageSetup;